#Wed Feb 18 19:31:01 UTC 2026
micronaut:
    application:
        name: jlogfmt

colors:
  info: 32   # зелёный
  warn: 33   # жёлтый
  error: 31  # красный
  debug: 36  # циан
  trace: 35  # пурпурный
  reset: 0   # сброс